### ISSUE TITLE
What happened to request interceptors?

### ISSUE THREAD

**Issue by chainlink** [Mitranim/xhttp#12]

**Comment by Mitranim** [comment]
They seem kinda pointless when you can just wrap `xhttp` into another function. In fact, wrapping is better because it doesn't modify the `xhttp` instance. The only piece of functionality that has been lost is accessing the xhr object before the request. If your use case demands, can add this back as an option.

**Comment by Mitranim** [comment]
Closing since this doesn't actually appear to be an issue.
