### ISSUE TITLE
how to request arraybuffer?

### ISSUE THREAD

**Issue by mspanish** [Mitranim/xhttp#15]
Hello looks very nice, I've been looking for a fetch replacement that has the ability to cancel. How about arraybuffer? Right now those are coming through as text, and I can't see a place for responseType to be set.  Thanks!

**Comment by mspanish** [comment]
I hacked it up to set xhr.responsType = 'arraybuffer' - and overrode the responseText to be response instead, as I'm only using this for binary stuff right now!  Would be nice to do this via params though :)

**Comment by Mitranim** [comment]
Hey there, glad you're finding this library useful!

The idea is to keep the native APIs accessible, while abstracting only the really annoying or hard-to-remember stuff. By this logic, setting `xhr.responseType` manually is a good thing, since it's easy to remember. But the library currently insists on using `xhr.responseText`, which is an issue.

The supposed way around this is by re-assembling the `Xhttp` function:

```js
import * as xhttp from 'xhttp'

export function binaryXhr(params, fun) {
  const xhr = new XMLHttpRequest()
  xhttp.xhrInitParams(xhr, params)
  xhttp.xhrSetMultiCallback(xhr, function onXhrDone(event) {
    const response = xhttp.eventToResponse(event)
    if (response.ok) fun({...response, body: xhr.response})
    else fun(response)
  })
  xhr.responseType = 'arraybuffer'
  xhttp.xhrStart(xhr)
  return xhr
}
```

This is probably more annoying than helpful; I have some ideas how to simplify this, but suggestions are welcome. Really want to avoid the over-configuration approach, since it leads to API bloat and loss of power. Curious about your thoughts.

**Comment by Mitranim** [comment]
I'm thinking of simplifying these utils to make the re-assembled version look like this:

```js
import * as xhttp from 'xhttp'

export function binaryXhr(params, fun) {
  const xhr = new XMLHttpRequest()
  xhr.responseType = 'arraybuffer'
  xhttp.start(xhr, xhttp.parseParams(params), function onXhrDone(event) {
    // This doesn't access xhr.response or xhr.responseText, so we're not paying any cost
    const response = xhttp.eventToResponse(event)
    const body = response.ok ? xhr.response : xhr.responseText
    fun({...response, body})
  })
  return xhr
}
```

Not sure how usable this would be to someone other than myself.

**Comment by mspanish** [comment]
hello @Mitranim - thanks so much for looking at this - and I totally understand the desire to reduce bloat. I really appreciate that about all of your libraries - I spent time last night looking through your lodash type replacement [espo](https://mitranim.com/espo/) and others - while I don't claim to understand all of your functions it sure makes for interesting reading! Guys like you make all of us better programmers. Even your [style library](https://mitranim.com/stylific/) is very lovely - I'm using a very slimmed down version of purecss - but I may grab some elements from there!  

For me the binaryXhr would be really useful - I encode all of my files in lz-string then in cbor - which turns svgs that would otherwise be 3 or 4 kb and turns the into like 300 bytes. I'm currently rewriting my svg db/editor [kwippe](https://kwippe.com) using Svelte and Rollup - and I've been really happy with the results so far. I really needed a way to cancel those fetches - as you pointed out in the docs of posterus - users cancel stuff all the time. They will click on a collection loading 50+ svgs, then before it finishes - click on another. Same with lots of other stuff. So I'm hoping to use your fns instead of fetch anytime more than 1 thing is being fetched.

I think most folks are just fetching json & text - but as the lack of cancellation is a glaring problem with fetch - more people may come to your library as adding 20K of bloat to your app just to get a cancel() fn is ridiculous! The bloat in JS is amazing - to think of how many times in the past I added 70kb min of Lodash to an app just to get 5 or 6 small functions!  My goal is to rewrite my entire app in less than 100KB - I think it's entirely possible using things like yours :)  So thanks again.

**Comment by Mitranim** [comment]
Thank you so much for the appreciation. 🙂 I never expected someone to randomly come and see value in my tools. Marketing is everything these days, while simplicity ain't.

The bloat in the ecosystem is why these tools exist. I just gave up on it; in the long run, writing everything from "scratch" (VM + standard library) is easier than dealing with unsatisfactory offerings. So I'm actually amazed that there are other people who feel the same. Thank you.

Btw since you mentioned Stylific: over the years, its most survivable part turned out to be the [layout shortcuts](https://mitranim.com/stylific/layout/#container) and primitive common-sense classes. Complex elements have low survival rates when you have many projects with different visual styles. I turned to reusing a [minimal reset/layout core](https://github.com/Mitranim/style-base) without any visual styles, and writing the rest more or less from scratch for each project. Not sure how this translates into other people's experiences.

Back to HTTP and the `binaryXhr` example. The idea is that it's written in the application code, and the library exists just to make this less annoying and give examples. Not sure if this makes sense. I'll probably go ahead and make the breaking API changes to make the second, simpler example viable.

**Comment by mspanish** [comment]
Well I'm surprised more people wouldn't have thanked you for your tools 😲. I hate marketing.  Seems to me that the programming mind is (or at least should be) the opposite of the one needed for marketing.  If you make something great, it's hard to see why the world needs you to convince them - after all you've just done them a favor anyway, lol. Yeah I cannot market to save my life - but I do like to create stuff, so I keep at it anyway!

Having minimal styles and writing stuff yourself seems  much better approach. Take [PureCSS](https://purecss.io/), for example. While the thing is getting a bit old, and doesn't even offer SCSS (the supposed SCSS repos are quite bloated and all broke my layout from the regular minified stock version) - and at 17KB min, that's still l lot of bloat just to get some layout, menu, forms, and buttons! And the responsive grid is extra.

But I took just their base CSS modules, commented out the ones like table that I didn't need - and got it down to 8 or 9 KB min - which is about all I think I'm willing to spend for just basics!

I will look at your [style-base](https://github.com/Mitranim/style-base). Maybe that will get me where I really want to be - which is indeed w/ a framework that is uber minimal and can survive from 1 project to the next.

You know what else I appreciate? That you don't refer to the GZIP as the "real size" of your libraries. That is always misleading - I mean the thing inflates back up and takes up memory and space in your app once it's transferred - so while it may help your initial page load faster, your app will still suffer from the same bloat as a non gzipped item! 

Please keep up the good work!

**Comment by Mitranim** [comment]
This is very encouraging. There's hope for the web 🙂

On the topic of the issue: I've rolled out a few changes to simplify "hacking" `xhttp`, and added an [example](https://github.com/Mitranim/xhttp/blob/947e4e4d54d856c4975a0eac2f7c97d4fb00fe08/readme.md#xhttpparams-fun) for binary data. Not sure if necessary, but should be nicer than before.

**Comment by mspanish** [comment]
Thanks very much, I'll check it out.  I'm trying to take time off this weekend for the holiday, but thought I'd try out style-base after. Taking time off... never easy to do when you're excited about a project! But my kids occasionally need a real meal or two :)
