### ISSUE TITLE
Status reports 200 when the actual status is 304 (not modified)

### ISSUE THREAD

**Issue by mspanish** [Mitranim/xhttp#17]
Hey I am trying to catch status 304, and I see that this gets reported as 200. Not sure it matters as the data is transferred anyway - is there a way to tell the request NOT to transfer data if it is a 304? If the user has already transferred a bunch of data that has not changed - I don't want them to re-download the same stuff. This is probably not the fault of your library just something I need to figure out!

**Comment by Mitranim** [comment]
I don't claim to fully understand how HTTP caching works, but here's what I've observed:

* when a browser has the asset cached and receives headers with the 304 status code, it should stop the request instead of downloading the body, saving the network traffic
* the browser will never tell you if it's 304 or 200
* for non-ajax requests, the browser will often serve the asset from memory or disk cache without hitting the network
* for ajax requests, the browser always seems to hit the network, but this might simply be due to having devtools open

If you want to guarantee that a particular request doesn't hit the network, and you're dead sure the file can't change or be deleted, cache the result manually in RAM.

**Comment by Mitranim** [comment]
Assuming this is not about `xhttp`. Closing the issue.
